# Generated by Django 6.0.5 on 2026-05-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_postagem', models.CharField(blank=True, max_length=45, null=True)),
                ('data_hora', models.CharField(blank=True, max_length=45, null=True)),
                ('conteudo', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
