# Generated by Django 5.2.15 on 2026-06-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_livro_options_biblioteca'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livro',
            table='livros',
        ),
    ]
