# Generated by Django 6.0.5 on 2026-05-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('data_nascimento', models.CharField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(blank=True, max_length=45, null=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('conquistas', models.CharField(blank=True, max_length=45, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil')),
            ],
        ),
    ]
